version: 2

jobs:
  build-java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: quarkus-mvc-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: quarkus-mvc-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn verify
      - store_test_results:
          path: target/surefire-reports

  build-java-11:
    docker:
        - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          key: quarkus-mvc-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: quarkus-mvc-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn verify
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build:
#    triggers:
#      - schedule:
#          cron: "14 3 * * *"
#          filters:
#            branches:
#              only:
#                - master
    jobs:
      - build-java-8
      - build-java-11