version: 2

jobs:
  build-java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: quarkus-mvc-2-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Prepare build
          command: mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: quarkus-mvc-2-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports

  build-java-11:
    docker:
        - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          key: quarkus-mvc-2-{{ .Branch }}-{{ checksum "pom.xml" }}
     - run:
         name: Prepare build
         command: mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: quarkus-mvc-2-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports

  quality-analysis:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: quarkus-mvc-2-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Run SonarCloud analysis
          command: |
            mvn -e org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_quarkus-mvc \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN

workflows:
  version: 2
  build:
    jobs:
      - build-java-8
      - build-java-11
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-java-8
      - build-java-11
      - quality-analysis